apiVersion: batch/v1
kind: Job
metadata:
  name: static-hydrate
spec:
  template:
    spec:
      containers:
      - name: hydrate
        image: omarlari/operator-demo-hydrate
        command: ["aws", "s3", "cp", "dynamic/index.html", "s3://olari-kube-created-this"]
      restartPolicy: Never
  backoffLimit: 1
