apiVersion: batch/v1
kind: Job
metadata:
  name: static-hydrate
spec:
  template:
    spec:
      containers:
      - name: hydrate
        image: omarlari/operator-demo-hydrate
        env:
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: aws-operator-workshop-101
                key: bucketName
        command: ["aws"]
        args: ["s3", "cp", "static/index.html", "s3://$(S3_BUCKET)"]
      restartPolicy: Never
  backoffLimit: 1
